# Generated by Django 3.0.6 on 2020-05-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20200514_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='downvotes',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='upvotes',
        ),
    ]
