# Generated by Django 3.0.6 on 2020-05-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_auto_20200514_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='vote_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='question',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='question',
            name='vote_score',
        ),
    ]
