# Generated by Django 3.0.6 on 2020-05-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_question_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
    ]
