# Generated by Django 3.0.6 on 2020-05-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0010_remove_question_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='question',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='question',
            name='vote_score',
        ),
    ]
